version: '3.8'

services:
  insightdeck-agent:
    build: .
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
    env_file:
      - .env
    volumes:
      - ./sample_data:/app/sample_data:ro
      - ./outputs:/app/outputs
    restart: unless-stopped